extends Node

enum GroupRating { MISS, OKAY, GOOD, PERFECT, BONUS }
enum Groups { SNAKE, CURVE, CURVE_SMALL, SINGLE_BONUS, CIRCLE_ROTATE, STRAIGHT }
enum GroupsSpecial { BIG_DIPPER, ORION, HERCULES, CAMELOPARDALIS, CEPHEUS }
